<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Grpc.Net.Client" Version="2.83.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\OSImageDeploy.Contracts\OSImageDeploy.Contracts.csproj" />
		<ProjectReference Include="..\OSImageDeploy.Engine\OSImageDeploy.Engine.csproj" />
		<ProjectReference Include="..\OSImageDeploy.Transport.Grpc\OSImageDeploy.Transport.Grpc.csproj" />
	</ItemGroup>

</Project>
